### ISSUE TITLE
Collect entropy on mobile devices

### ISSUE THREAD

**Issue by zuf** [vibornoff/entropy-collector.js#1]
Is it possible to collect entropy on mobile devises with touch events?

**Comment by vibornoff** [comment]
Short answer is "not yet".

Not sure if touch events generate `mousemove`s.
Suppose it's better to collect accelerometer and g-sensor events rather then taps.

This feature isn't yet implemented. If you're willing to implement it on your own, I would be glad to review your participation and let your patch in.
